tap "elastic/tap"
tap "getsentry/tools"
tap "gromgit/fuse"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "nodenv/nodenv"
tap "rcmdnk/file"
brew "actionlint"
brew "anyenv"
brew "apr-util"
brew "automake"
brew "awscli"
brew "bat"
brew "berkeley-db", link: true
brew "glib"
brew "certbot"
brew "circleci"
brew "openldap"
brew "curl"
brew "fdk-aac"
brew "libtool"
brew "freetds"
brew "gdk-pixbuf"
brew "gh"
brew "ghq"
brew "gibo"
brew "git"
brew "git-flow"
brew "gnu-sed"
brew "unbound"
brew "gnutls"
brew "gnupg"
brew "go"
brew "gobject-introspection"
brew "goenv"
brew "harfbuzz"
brew "pango"
brew "librsvg"
brew "graphviz"
brew "guile"
brew "httpd"
brew "hub"
brew "shared-mime-info"
brew "x265"
brew "imagemagick"
brew "jq"
brew "krb5"
brew "lame"
brew "leptonica"
brew "libarchive"
brew "libass"
brew "libfido2"
brew "libpq"
brew "libvorbis"
brew "opus"
brew "libvpx"
brew "mas"
brew "mecab"
brew "mecab-ipadic"
brew "mp3info"
brew "mysql-client"
brew "nasm"
brew "nghttp2"
brew "nginx"
brew "node-build"
brew "nodenv"
brew "openapi-generator"
brew "peco"
brew "postgresql@13", restart_service: true
brew "postgresql@14", restart_service: true
brew "protobuf"
brew "pwgen"
brew "pyenv"
brew "python@3.10"
brew "python@3.9"
brew "ruby-build"
brew "rbenv"
brew "redis", restart_service: true
brew "rename"
brew "ripgrep"
brew "ruby"
brew "sdl12-compat"
brew "shtool"
brew "sox"
brew "srt"
brew "swagger-codegen"
brew "tesseract"
brew "texi2html"
brew "theora"
brew "tree"
brew "vim"
brew "wget"
brew "x264"
brew "xvid"
brew "yarn"
brew "zsh"
brew "getsentry/tools/sentry-cli"
brew "nodenv/nodenv/node-build-update-defs"
brew "rcmdnk/file/brew-file"
cask "alfred"
cask "alt-tab"
cask "aws-vault"
cask "barrier"
cask "chromedriver"
cask "dbeaver-community"
cask "deepl"
cask "flipper"
cask "google-chrome"
cask "iterm2"
cask "karabiner-elements"
cask "macfuse"
cask "postman"
cask "rancher"
cask "slack"
cask "timer"
cask "visual-studio-code"
cask "zoom"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Smart Countdown Timer", id: 1410709951
mas "Spark", id: 1176895641
mas "Xcode", id: 497799835
vscode "MS-CEINTL.vscode-language-pack-ja"
