# env / PATH と各種ツール初期化。dot_zshrc から source（options の compinit 後に読む）。

# --- PATH の土台を保証（非ログインシェル対策） ---
# VS Code 端末 / tmux / 手動起動の zsh などの非ログインシェルでは ~/.zprofile が走らず、
# Homebrew と macOS 標準の bin が PATH から抜けて git/awk 等が command not found になる。
# ログインシェルでは既に載っているため何もしない（冪等）。欠けているときだけ補う。
if [[ -x /opt/homebrew/bin/brew && ":$PATH:" != *":/opt/homebrew/bin:"* ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"   # /opt/homebrew/{bin,sbin} を前置
fi
# macOS 標準ディレクトリ（awk 等）。ツールの上書きを避けるため末尾に、無い場合のみ追加。
for _d in /usr/bin /bin /usr/sbin /sbin; do
  [[ ":$PATH:" != *":$_d:"* ]] && export PATH="$PATH:$_d"
done
unset _d

export AWS_PROFILE=grit

# Added by serverless binary installer
export PATH="$HOME/.serverless/bin:$PATH"
export GPG_TTY=$(tty)

# バージョンマネージャは mise に統合（node/python/java は ~/.config/mise/config.toml）
# go は Homebrew、ruby は macOS system を利用。旧 nodenv/goenv/pyenv/rbenv/jenv/anyenv は温存だが未初期化。
eval "$(mise activate zsh)"
# mise の JAVA_HOME は precmd フックで遅延設定されるため、ここでは mise where で確定的に解決する。
export ES_JAVA_HOME="$(mise where java 2>/dev/null)"   # mise の java(temurin-11) を Elasticsearch へ

export PATH="/Users/kokikono/.local/bin:$PATH"

# grit
export GRIT_INSTALL="$HOME/.grit"
export PATH="$GRIT_INSTALL/bin:$PATH"

export PATH="/opt/homebrew/opt/mysql-client/bin:$PATH"

# bun completions
[ -s "/Users/kokikono/.bun/_bun" ] && source "/Users/kokikono/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

#compdef wtp
compdef _wtp wtp

# This is a shell completion script auto-generated by https://github.com/urfave/cli for zsh.

_wtp() {
	local -a opts # Declare a local array
	local current
	current=${words[-1]} # -1 means "the last element"
	if [[ "$current" == "-"* ]]; then
		# Current word starts with a hyphen, so complete flags/options
		opts=("${(@f)$(env WTP_SHELL_COMPLETION=1 ${words[@]:0:#words[@]-1} ${current} --generate-shell-completion)}")
	else
		# Current word does not start with a hyphen, so complete subcommands
		opts=("${(@f)$(env WTP_SHELL_COMPLETION=1 ${words[@]:0:#words[@]-1} --generate-shell-completion)}")
	fi

	if [[ "${opts[1]}" != "" ]]; then
		_describe 'values' opts
	else
		_files
	fi
}

# Don't run the completion function when being source-ed or eval-ed.
# See https://github.com/urfave/cli/issues/1874 for discussion.
if [ "$funcstack[1]" = "_wtp" ]; then
	_wtp
fi

# wtp cd command hook for zsh
wtp() {
    for arg in "$@"; do
        if [[ "$arg" == "--generate-shell-completion" ]]; then
            command wtp "$@"
            return $?
        fi
    done
    if [[ "$1" == "cd" ]]; then
        local target_dir
        if [[ -z "$2" ]]; then
            target_dir=$(command wtp cd 2>/dev/null)
        else
            target_dir=$(command wtp cd "$2" 2>/dev/null)
        fi
        if [[ $? -eq 0 && -n "$target_dir" ]]; then
            cd "$target_dir"
        else
            if [[ -z "$2" ]]; then
                command wtp cd
            else
                command wtp cd "$2"
            fi
        fi
    elif [[ "$1" == "add" ]]; then
        for arg in "$@"; do
            if [[ "$arg" == "--help" || "$arg" == "-h" ]]; then
                command wtp "$@"
                return $?
            fi
        done

        if [[ ! -t 1 ]]; then
            command wtp "$@"
            return $?
        fi

        local target_dir
        target_dir=$(command wtp "$@" --quiet)
        local wtp_status=$?
        if [[ $wtp_status -eq 0 && -n "$target_dir" ]]; then
            cd "$target_dir" || return $?
        fi
        return $wtp_status
    else
        command wtp "$@"
    fi
}

# Google Cloud SDK（Homebrew cask: gcloud-cli）。path.zsh.inc で SDK の全 bin（コンポーネント含む）を
# PATH に追加し、completion.zsh.inc で補完を有効化する。
if [ -f "/opt/homebrew/share/google-cloud-sdk/path.zsh.inc" ]; then . "/opt/homebrew/share/google-cloud-sdk/path.zsh.inc"; fi
if [ -f "/opt/homebrew/share/google-cloud-sdk/completion.zsh.inc" ]; then . "/opt/homebrew/share/google-cloud-sdk/completion.zsh.inc"; fi
